### model
# model_name_or_path: /data1/choins18/moe/LLaMA-Factory/Distill_MoEv2_vanillaSynced
model_name_or_path: /data1/choins18/distill_moe/LLaMA-Factory/Distill_MoEv2
# model_name_or_path: TinyLlama/TinyLlama_v1.1
# trust_remote_code: true

### method
stage: pt
do_train: true
# finetuning_type: full
finetuning_type: freeze
freeze_trainable_modules: mlp, self_attn
freeze_trainable_layers: 22
# freeze_extra_modules : norm, lm_head
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: SlimPajama6B_train_1B
# dataset: c4_demo
cutoff_len: 1024
overwrite_cache: true
packing: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/1B/distill_moe_full_MSE
logging_steps: 10
save_steps: 300
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: distill_moe_full_MSE_1B

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
# num_train_epochs: 3.0 
# lr_scheduler_type: linear
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs: {'min_lr': 1.0e-5}
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
# ddp_find_unused_parameters: true
# gradient_checkpointing: true
# gradient_checkpointing_kwargs: {"use_reentrant": true}

### eval
# eval_dataset: SlimPajama6B_val_1over6
val_size: 0.1
# val_size: 0.01
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 300